### PR TITLE
Mailing list form

### PR DESCRIPTION
**Pull request by brandenbyers**
Added a mailing list subscription form to the footer of every page. The backend for the form is a Google Form. These email addresses are saved to a spreadsheet, and then that spreadsheet can be manually uploaded to SendGrid before each newsletter goes out (this should be automated at some point).

### CODE REVIEW

**Comment by jetpacktuxedo** [comment]
So does this mean we have an address we plan to use?

**Comment by brandenbyers** [comment]
What do you mean?

**Comment by jetpacktuxedo** [comment]
Wasn't the reason that we didn't have a mailing list yet because mailing lists were required to list a physical address and none of us wanted to use our own?

**Comment by brandenbyers** [comment]
We don’t need an address to _collect_ email addresses. We get a few requests to be added to a mailing list via our contact form. So I figure we should at least make it easy to collect them. And I’ll explain my idea for a newsletter at the board meeting tonight.

**Pull request merged**
